### ISSUE TITLE
Add Test Partitions to Development Cluster

### ISSUE THREAD

**Issue by Comeani** [pitt-crc/Slurm-Test-Environment#69]
When setting up some functionality in https://github.com/pitt-crc/bank/pull/223 for locking when investment partitions are present, `sinfo` is used to gather a list of partitions. This is currently empty, and example output is provided with an `@patch.object` statement. 

Possibly related to this, whenever I call the `Slurm.partition_names` function from the debugging console without the patch in place, I get the following error output:

```
Error
Traceback (most recent call last):
  File "/opt/project/tests/account_logic/test_AccountServices.py", line 48, in test_account_locked_on_cluster
    account_services.lock(clusters=[settings.test_cluster])
  File "/opt/project/bank/account_logic.py", line 904, in lock
    self._set_account_lock(True, clusters, all_clusters)
  File "/opt/project/bank/account_logic.py", line 887, in _set_account_lock
    for partition in [Slurm.partition_names(cluster)]:
  File "/opt/project/bank/system/slurm.py", line 64, in partition_names
    cmd.raise_if_err()
  File "/opt/project/bank/system/shell.py", line 50, in raise_if_err
    raise CmdError(self.err)
bank.exceptions.CmdError: slurm_load_partitions: Unable to contact slurm controller (connect failure)
```

**Comment by Comeani** [comment]
Possibly related to #65, I can run the same `ShellCmd` command immediately after the first and the correct results are returned. I thought it was just inconsistently having the issue, but it turns out that the controller is down on the first attempt: 

```
>>> ShellCmd("scontrol ping").out.split("\n")

PyDev console: starting.
['Slurmctld(primary) at 2d8610b69a80 is DOWN', '*****************************************', '** RESTORE SLURMCTLD DAEMON TO SERVICE **', '*****************************************']

>>> ShellCmd("scontrol ping").out.split("\n")

['Slurmctld(primary) at 2d8610b69a80 is UP']

>>> cmd = ShellCmd(f'sinfo -M {cluster} -o "%P" --noheader')
>>> cmd.out
'normal*\ndebug'
```

**Comment by djperrefort** [comment]
I don't get this problem in bash:

```bash
docker run -it [IMAGE NAME] bash

[root@7f3ac29cebcd /]# scontrol ping
Slurmctld(primary) at 7f3ac29cebcd is UP
```
